language: cpp

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T HW2_IP_FILTER-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uAZ015:$BINTRAY_API_KEY "https://api.bintray.com/content/OTUS_HW/homework_2/HW2_IP_FILTER/$TRAVIS_BUILD_NUMBER/HW2_IP_FILTER-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 
